harvest:
  account: my-company
  username: bugyield@mycompany.com
  password: 1234
  ssl: true
  #projects: "alias,name,id,all,active" # Currently deprecated/unsupported
  daysback: 0
  exclude_contractors: true
settings:
  # used for geekometers - as of v0.4 these values are still hardcoded. Sigh.
  #max_billable_hours_per_day: 75
  #min_billable_hours_per_day: 0
budget: 
  #billable hours in our budget pr. month
  employee:
    2012:
      jan: 123
      feb: 123
      mar: 123
      apr: 123
      may: 123
      jun: 123
      jul: 123
      aug: 123
      sep: 123
      oct: 123
      nov: 123
      dec: 123